PATCH http://localhost:8000/api/user/updateProfile
Content-Type: application/json

{
  "email": "abcxyz0101201@gmail.com",
  "gitHub": "Aditya-Pandey-GH",
  "leetCode": "Aditya-Pandey-LC"
}


###

GET http://localhost:8000/api/user?email=abcxyz0101201@gmail.com